# Generated by Django 4.2 on 2023-04-21 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('easyjob', '0002_freelancers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Сфера'),
        ),
        migrations.AlterField(
            model_name='freelancers',
            name='about_freelance',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='freelancers',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='freelancers',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='easyjob.category', verbose_name='Сфера'),
        ),
        migrations.AlterField(
            model_name='freelancers',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='freelancers',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='freelancers',
            name='time_create',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_vacancy', models.CharField(max_length=30, verbose_name='')),
                ('salary_vacancy', models.IntegerField(verbose_name='Зарплата')),
                ('experience_vacancy', models.IntegerField(verbose_name='Опыт работы')),
                ('skills_vacancy', models.CharField(max_length=100, verbose_name='Требуемые навыки')),
                ('about_vacancy', models.TextField(verbose_name='О вакансии')),
                ('time_create', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='easyjob.category', verbose_name='Сфера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
