# Generated by Django 4.2 on 2023-04-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyjob', '0003_alter_category_name_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='title_vacancy',
            field=models.CharField(max_length=30, verbose_name='Наименование вакансии'),
        ),
    ]
